config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  root 'pages#home'
  get 'pages/contact' => 'pages#contact', as: 'contact'
  get 'users/community' => 'users#community', as: 'community'
  get 'users/:id' => 'users#show', as: 'users'

  post 'users/:id/follow' => 'users#follow', as: 'follow'
  post 'users/:id/unfollow' => 'users#unfollow', as: 'unfollow'
  get 'pages/search/:id/artist' => 'pages#searchArtist', as: 'searchArtist'
  get 'pages/search/:id/album' => 'pages#searchAlbum', as: 'searchAlbum'
  get 'pages/search/:id/track' => 'pages#searchTrack', as: 'searchTrack'
  get 'pages/results' => 'pages#resultsPage', as: 'results'

  resources :song_reviews, only: [:create, :index, :show, :edit, :update, :new]
  resources :album_reviews, only: [:create, :index, :show, :edit, :update, :new]
  resources :song_reviews, only: [:destroy]
  resources :album_reviews, only: [:destroy]
end

app/models/album_review.rb
class AlbumReview < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song_review.rb
class SongReview < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/album_reviews_controller.rb
class AlbumReviewsController < ApplicationController
  def show
    @album = MusicAPI.new.findAlbum(params[:id])
    artistid = @album.artists[0].id
    @artist = MusicAPI.new.findArtist(artistid)
    @album_review = AlbumReview.new
    @reviews = AlbumReview.where("api_id LIKE ?", "%#{params[:id]}%")
    @tracks = @album.tracks
    @finalsum = rating_score
  end

  def create
    @album_review = AlbumReview.new(review_params)
    @album = MusicAPI.new.findAlbum(params[:id])
    albumid = @album_review.api_id
    if @album_review.save
      redirect_to album_review_path(albumid)
    else
      render :show
    end
  end

  def rating_score
    sum = 0
    @reviews.each do |review|
      if review.rating
    sum += review&.rating
      end
    end
    @reviews&.count&.zero? ? '0.0' : (sum / @reviews.count.to_f)
  end

  def destroy
    @album_review = AlbumReview.find(params[:id])
    @album_review.destroy
    albumid = @album_review.api_id
    redirect_to album_review_path(albumid)
  end

  def review_params
    params.require(:album_review).permit(:description, :rating, :api_id, :user_id, :title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  RSpotify.authenticate(ENV['spotify_client_id'], ENV['spotify_secret_key'])

  include Pundit::Authorization

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(root_path)
  end
  # STEPS TO ENABLE AUTH IN A CONTROLLER
  # Add to controllers code to fix authorize error
  # authorize @instance_variable_name
  # Create Policy
  # rails g pundit:policy NAME ie restuarant
  # Edit Policy
  # inside the new polciy.rb create a function
  # Use if Statement in View
  # if policy() .....

  private

  # =~ /(^(rails_)?admin)|(^pages$)/

  def skip_pundit?
    devise_controller? || params[:controller]
    # Temp turned off until project week where it will be decided by team if we would like to implement
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :photo, :description])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @artists1 = MusicAPI.new.displayArtist('bee gee')
    @artists2 = MusicAPI.new.displayArtist('arianna')
    @artists3 = MusicAPI.new.displayArtist('vance')
    @artists4 = MusicAPI.new.displayArtist('kate bush')
    @artists5 = MusicAPI.new.displayArtist('Beyoncé')
    @albums = MusicAPI.new.displayAlbums('lil')
    @tracks = MusicAPI.new.displayTracks('bush')
  end

  def searchArtist
    # if general search term is provided, search for artist, album, and track
    if params[:searchText]
      @resultsArtist = MusicAPI.new.findArtist(params[:searchText])
      @top_tracks = @resultsArtist.top_tracks(:US)
      @top_albums = @resultsArtist.albums(limit: 8, country: 'US')
    else
      @resultsArtist = MusicAPI.new.findArtist(params[:id])
      @top_tracks = @resultsArtist.top_tracks(:US)
      @top_albums = @resultsArtist.albums(limit: 8, country: 'US')
    end
  end

  def searchTrack
    @resultsTrack = MusicAPI.new.findTrack(params[:id])
  end

  def resultsPage
    @query = params[:searchText]['query'];
    @results_artist = MusicAPI.new.displayArtist(params[:searchText]['query']);
    @results_album = MusicAPI.new.displayAlbums(params[:searchText]['query']);

    @results_more_artists = MusicAPI.new.display_more_artists(params[:searchText]['query']);
    @results_more_albums = MusicAPI.new.display_more_albums(params[:searchText]['query']);
    @results_more_tracks = MusicAPI.new.display_more_tracks(params[:searchText]['query']);
  end

  def contact
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    def after_update_path_for(resource)
      users_path(resource)
    end
end

app/controllers/song_reviews_controller.rb
class SongReviewsController < ApplicationController
  def show
    @song = MusicAPI.new.findTrack(params[:id])
    album_id = @song.album.id
    @album = MusicAPI.new.findAlbum(album_id)
    @song_review = SongReview.new
    @reviews = SongReview.where("api_id LIKE ?", "%#{params[:id]}%")
    @tracks = @album.tracks
  end

  def create
    @song_review = SongReview.new(review_params)
    @song = MusicAPI.new.findTrack(params[:id])
    songid = @song_review.api_id
    if @song_review.save
      redirect_to song_review_path(songid)
    else
      render :show
    end
  end

  def destroy
    @song_review = SongReview.find(params[:id])
    @song_review.destroy
    songid = @song_review.api_id
    redirect_to song_review_path(songid)
  end

  def review_params
    params.require(:song_review).permit(:description, :rating, :api_id, :user_id, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @album_reviews = AlbumReview.where(user_id: @user.id)
    @song_reviews = SongReview.where(user_id: @user.id)
  end

  def community
    @user = User.all
    @all_album_reviews = AlbumReview.all
    @all_song_reviews = SongReview.all
  end

  def follow
    @user = User.find(params[:id])
    userid = @user.id
    current_user.following.push(userid)
    @user.followers.push(current_user.id)
    @user.save
    current_user.save
    redirect_to users_path(@user)
  end


  def unfollow
    @user = User.find(params[:id])
    userid = @user.id
    current_user.following.delete(userid)
    @user.followers.delete(current_user.id)
    @user.save
    current_user.save
    redirect_to users_path(@user)
  end
end

app/helpers/album_reviews_helper.rb
module AlbumReviewsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/song_reviews_helper.rb
module SongReviewsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/album_reviews/show.html.erb
<div class="album-banner p-3 d-flex justify-content-end">
  <div class="album-img">
    <img src="<%= @album.images[0]&.url %>" class="album-img border border-dark border-4 p-2" alt="">
  </div>
  <div class="container album-details">
    <div class="album-box">
      <%= render "partials/rating-box", data:@finalsum.to_f.round(1)%>
    </div>
    <div class="album-info">
      <div class="album-details d-flex justify-content-between align-items-end border-bottom border-dark me-3">
        <div>
          <h1 class='album-name'><%= @album&.name %> </h1>
        </div>
        <div>
          <p class="songs">Album-<%= @album.total_tracks%>  Tracks- <%= @album.release_date.split("-").first %></p>
        </div>
      </div>
      <h4 class="artist-nm"><%= @album.artists[0]&.name %></h4>
    </div>
  </div>
  <div class="album-review p-5" >
    <%= simple_form_for [ @album_review ] do |f| %>
      <%= f.input :description , as: :text, :input_html => { :rows => 3 }, placeholder: "Post a review here!", label: false%>
      <p class="rating-text border-bottom border-dark">Pick Your Rating!</p>
      <%= f.input :rating, collection: 0..5, label: false %>
      <%= f.input :title, as: :hidden, input_html: { value: @album.name }  %>
      <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
      <%= f.input :api_id, as: :hidden, input_html: { value: @album.id } %>
      <%= f.submit "Submit review", class: "btn-main px-5 rounded-modal album-submit"%>
    <% end %>
  </div>
</div>
<div class='row'>
  <div class='col-lg-6 col-md-6 col-sm-12 ps-5'>
    <div class="display-songs mt-3">
      <h2>Tracks</h2>
      <hr>
      <ul class = "reviewed-songs">
        <% @tracks.each do |track| %>
          <li class = "song-item">
            <div class = "song-info">
              <div class = "rating-box-artist"> <%= render "partials/rating-box", data: (track.popularity/20.to_f).round(1) %></div>
              <div class = "song-name"><%= track.name %></div>
            </div>
            <%= link_to "Reviews", song_review_path(track.id), class: "song-reviews" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class='col-lg-6 col-md-6 col-sm-12 pe-5'>
    <div class="mt-3" >
      <h2 class="ms-3">Hot Reviews</h2>
      <hr>
      <div class="display-reviews">
        <% if @reviews.empty? %>
          <h1 class ="text-center fw-semibold fs-4">
            There are currently no reviews for this album.
          </h1>
        <% else %>
          <div class="reviews p-2">
            <% @reviews.each do |review|%>
              <a href="/users/<%= review.user_id %>" class="modal-links">
                <div>
                  <%= cl_image_tag User.find(review.user_id).photo.key, class:'review-user-image border border-dark ms-3 me-2'%>
                  <span><%=User.find(review.user_id).username%></span>
                </div>
              </a>
              <div class="display-album-reviews">
                <div class="album-description">
                  <i class="fas text-muted fa-quote-left me-2"></i><%= review&.description %> <i class="fas text-muted fa-quote-right me-2"></i>
                </div>
                <div class="album-rating">
                  <%= render "partials/rating-box", data:review&.rating.to_f%>
                  <% if review.user_id == current_user.id %>
                    <%= button_to "Delete", album_review_path(review.id), class: 'btn link-danger hover-icon hide-btn-js', method: :delete, data: { disable_with: "Please wait..." } %>
                  <% end %>
                </div>
              </div>
              <hr>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title>Noted - A music platform that brings music lovers together to share there reviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <%= yield %>
    <%= render "partials/footer" %>
    <script src="https://unpkg.com/scrollreveal"></script>
  </body>
</html>

app/views/pages/contact.html.erb
<span class="stamp is-approved">HIRED</span>

app/views/pages/home.html.erb
<%= render "partials/hero" %>
<div class='container'>
  <h2 class='m-3 homepage-heading'>Popular Artists</h2>
  <hr/>
  <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
    <% @artists2[0...1]&.each do |artist| %>
      <a href=<%="pages/search/#{artist&.id}/artist"%> class='link-dark text-decoration-none'>
        <div class="col ">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg noted-home-image" style="background-image: url('<%= artist&.images[0]&.url  %>');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold blend-noted"><%= artist&.name %></h3>
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                </li>
                <li class="d-flex align-items-center">
                </li>
              </ul>
            </div>
          </div>
        </div>
      </a>
    <% end %>
    <% @artists3[0..2]&.each do |artist| %>
      <a href=<%="pages/search/#{artist&.id}/artist"%> class='link-dark text-decoration-none'>
        <div class="col ">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg noted-home-image" style="background-image: url('<%= artist&.images[0]&.url  %>');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold blend-noted"><%= artist&.name %></h3>
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                </li>
                <li class="d-flex align-items-center">
                </li>
              </ul>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
  <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
    <% @artists1[0...1]&.each do |artist| %>
      <a href=<%="pages/search/#{artist&.id}/artist"%> class='link-dark text-decoration-none'>
        <div class="col ">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg noted-home-image" style="background-image: url('<%= artist&.images[0]&.url  %>');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold blend-noted"><%= artist&.name %></h3>
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                </li>
                <li class="d-flex align-items-center">
                </li>
              </ul>
            </div>
          </div>
        </div>
      </a>
    <% end %>
    <% @artists4[0..1]&.each do |artist| %>
      <a href=<%="pages/search/#{artist&.id}/artist"%> class='link-dark text-decoration-none'>
        <div class="col ">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg noted-home-image" style="background-image: url('<%= artist&.images[0]&.url  %>');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold blend-noted"><%= artist&.name %></h3>
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                </li>
                <li class="d-flex align-items-center">
                </li>
              </ul>
            </div>
          </div>
        </div>
      </a>
    <% end %>
    <% @artists5[0...1]&.each do |artist| %>
      <a href=<%="pages/search/#{artist&.id}/artist"%> class='link-dark text-decoration-none'>
        <div class="col ">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg noted-home-image" style="background-image: url('<%= artist&.images[0]&.url  %>');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold blend-noted"><%= artist&.name %></h3>
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                </li>
                <li class="d-flex align-items-center">
                </li>
              </ul>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
  <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
  </div>
  <h2 class='m-3 homepage-heading'>Popular Albums</h2>
  <hr/>
  <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
    <% @albums.each do |album| %>
      <a href=<%="/album_reviews/#{album.id}"%> class='link-dark text-decoration-none'>
        <div class="col">
          <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg noted-home-image" style="background-image: url('<%= album.images[0]&.url %>');">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <ul class="d-flex list-unstyled mt-auto">
                <li class="me-auto">
                  <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold blend-noted"><%= album.name %></h3>
                </li>
                <li class="d-flex align-items-center me-3">
                  <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"></use></svg>
                </li>
                <li class="d-flex align-items-center">
                </li>
              </ul>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/pages/searchTrack.html.erb
<%= @resultsTrack %>

app/views/partials/_navbar.html.erb
<header class="noted-bg flex-grow-1">
  <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 4.5fr 2fr;">
    <a href="/" class="d-flex link-dark text-decoration-none navbar-link">
      <img src='https://res.cloudinary.com/dh8a307rs/image/upload/v1657791144/Artboard_3_tztpx9.png' class='noted-img'>
    </a>
    <div class="d-flex align-items-center">
      <div class='w-100 me-3 search-icon'>
        <img src='https://res.cloudinary.com/dh8a307rs/image/upload/v1657936047/Search_Icon_jcmkgq.png' class='search-pic'>
        <%= simple_form_for :searchText, url: results_path,  method: :get do |f| %>
          <input type="search" class="form-control search-bar" aria-label="Search" name="searchText[query]">
        <% end %>
      </div>
      <div class="flex-shrink-0 dropdown">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://res.cloudinary.com/dh8a307rs/image/upload/v1657936046/Group_29_fuv0ij.png" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
          <% if user_signed_in? %>
            <li><a class="dropdown-item" href="/users/<%=current_user.id %>">Profile</a></li>
            <li><a class="dropdown-item" href="/users/community">Community</a></li>
          <% end %>
          <li><hr class="dropdown-divider"></li>
          <% if user_signed_in? %>
            <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "LOG IN", new_user_session_path, class: "dropdown-item" %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>
<%# <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button> %>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row user-banner">
    <div class="col col-sm-12 col-md-6 my-5" >
      <div class="user-banner-left d-flex flex-column justify-content-center align-items-center">
        <% unless @user.photo.key == nil %>
          <%= cl_image_tag @user&.photo&.key, class:'profile-img mb-5' %>
        <% else %>
          <img src='https://res.cloudinary.com/dh8a307rs/image/upload/v1657976924/fireworks_1_tscv62.png' class='profile-img mb-5'>
        <% end %>
        <div>
          <% if @user&.followers&.include?(current_user&.id) && @user&.id != current_user&.id %>
            <%=  link_to "Unfollow", unfollow_path, method: :post, class:"btn btn-main btn-lg rounded-modal text-dark px-4 py-1" %>
          <%elsif @user&.id != current_user&.id&.to_i%>
            <%= link_to "Follow", follow_path, method: :post, class:"btn btn-main btn-lg rounded-modal text-dark px-4 py-1" %>
          <% end %>
          <% if @user.id === current_user.id %>
            <%=  link_to "Edit", edit_user_registration_path, class:"btn btn-main btn-lg rounded-modal text-dark px-4 py-1" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col col-sm-12 col-md-6 d-flex align-items-center">
      <div class="user-banner-right d-flex flex-column justify-content-between w-100">
        <div class="d-flex justify-content-between align-items-start">
          <div class="fs-1">
            <h1>
              <%=@user&.first_name %>
              <%= @user&.last_name %>
            </h1>
            <span class="fs-6 text-muted">@<%= @user&.username %></span>
          </div>
          <div class="d-flex me-5">
            <div type="button" data-bs-toggle="modal" data-bs-target="#followers-modal" class="text-center">
              <h5 class="me-3">Followers</h5>
              <h5><%= @user&.followers.length %></h5>
            </div>
            <div type="button" data-bs-toggle="modal" data-bs-target="#following-modal" class="text-center">
              <h5>Following</h5>
              <h5><%= @user&.following.length %></h5>
            </div>
          </div>
        </div>
        <div>
          <div>
            <hr class="solid mb-3">
            <h5 class="fs-3">About Me</h5>
            <p class="mb-3"><%= @user.description %></p>
            <div class="user-info d-flex justify-content-start py-3">
              <div class="d-flex flex-column me-3">
                <span class="fs-5">Rated Albums</span>
                <span class="fw-bold fs-3 text-center"> <%= @album_reviews.count  %></span>
              </div>
              <div class="d-flex flex-column me-3">
                <span class="fs-5">Rated Songs</span>
                <span class="fw-bold fs-3 text-center"><%= @song_reviews.count %></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container my-5" id="recent-reviews-album">
    <div class="d-flex justify-content-between align-items-end">
      <h2 class="fs-2">Your Recent Album Reviews</h2>
    </div>
    <hr class="solid mb-3">
    <div class="row">
      <div class="col-sm-12 col-md-6 col-lg-8">
        <div>
          <div class="mb-3 d-flex align-items-end">
            <%= render "partials/rating-box", class: "me-5", data:@album_reviews[-1]&.rating.to_f %>
            <h5><%= @album_reviews[-1]&.title %></h5>
          </div>
          <%= @album_reviews[-1]&.description %>
        </div>
      </div>
      <div class="col-sm-12 col-md-6 col-lg-4">
        <%= render "partials/quad_tracks", data:@album_reviews, class:"d-flex align-items-end" %>
      </div>
    </div>
  </div>
  <div class="container mt-5" id="recent-reviews-song">
    <div class="d-flex justify-content-between align-items-end">
      <h2 class="fs-2">Your Recent Song Reviews</h2>
    </div>
    <hr class="solid mb-3">
    <div class="row">
      <div class="col-sm-12 col-md-6 col-lg-8">
        <div>
          <div class="mb-3 d-flex align-items-end">
            <%= render "partials/rating-box", class: "me-5", data:@song_reviews[-1]&.rating %>
            <h5><%= @song_reviews[-1]&.title %></h5>
          </div>
          <%= @song_reviews[-1]&.description %>
        </div>
      </div>
      <div class="col-sm-12 col-md-6 col-lg-4">
        <%= render "partials/quad_tracks_songs", data:@song_reviews, class:"d-flex align-items-end" %>
      </div>
    </div>
  </div>
  <div class="modal fade" id="followers-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content rounded-modal">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Followers</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <% @user.followers.each do |id|%>
            <%[User.find(id)].each do |user|%>
              <a href="/users/<%= user.id %>" class="modal-links">
                <div class="mb-3">
                  <%= cl_image_tag user&.photo&.key, class:'avatar me-2' %>
                  <%= user.username %>
                </div>
              </a>
            <% end %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-main rounded-modal" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="following-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content rounded-modal">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Following</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <% @user.following.each do |id|%>
            <%[User.find(id)].each do |user|%>
              <a href="/users/<%= user.id %>" class="modal-links">
                <div class="mb-3">
                  <%= cl_image_tag user&.photo&.key, class:'avatar me-2'%>
                  <%= user&.username %>
                </div>
              </a>
            <% end %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-main rounded-modal" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>